platform :ios, '9.0'

inhibit_all_warnings!

target 'ReactorCore' do
  use_frameworks!

  pod 'ReactiveSwift'

	pod 'SwiftFormat/CLI'

  target 'ReactorCoreTests' do
  	inherit! :search_paths
  end
end